### ISSUE TITLE
Deprecation warning on initial install

### ISSUE THREAD

**Issue by meltinglava** [apemangr/Condor-Emacs#1]
Just did a clean startup (as i wanted to test this project. got the warning: `Package cl is deprecated
`
```
emacs --version
GNU Emacs 27.0.50
```

**Comment by apemangr** [comment]
Can you send a screenshot?

**Comment by apemangr** [comment]
Yes, that was due to the use of an obsolete package, the version you downloaded was tested in emacs 26.3, currently everything works fine in version 28 of emacs.
